In [16]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf

In [17]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [18]:
mnist = tf.keras.datasets.mnist

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [19]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [20]:
predictions = model(x_train[:1]).numpy()
predictions


array([[-0.308815  , -0.29869875, -0.5185604 ,  0.40336883, -0.10790613,
         1.040886  ,  0.28770548, -0.08650881,  0.40596876,  0.19254412]],
      dtype=float32)

In [21]:
tf.nn.softmax(predictions).numpy()

array([[0.05988873, 0.06049765, 0.04855721, 0.12207945, 0.07321477,
        0.23094724, 0.10874534, 0.07479824, 0.12239727, 0.0988741 ]],
      dtype=float32)

In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [23]:
loss_fn(y_train[:1], predictions).numpy()


1.465566

In [24]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [25]:
model.fit(x_train, y_train, epochs=5)


2022-06-08 15:35:44.097648: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2972 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1405 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1047 - accuracy: 0.9688
Epoch 4/5
1054/1875 [===============>..............] - ETA: 1s - loss: 0.0826 - accuracy: 0.9743

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

2022-06-08 15:34:20.985207: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.


313/313 - 0s - loss: 0.0742 - accuracy: 0.9778 - 442ms/epoch - 1ms/step


[0.07417333126068115, 0.9778000116348267]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax() ])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.13762359e-07, 2.67973088e-09, 5.68764199e-06, 6.12466611e-05,
        4.50231831e-11, 9.36191725e-07, 5.71473112e-11, 9.99930739e-01,
        3.61488361e-07, 4.55382690e-07],
       [5.40230587e-07, 7.88098434e-04, 9.99029398e-01, 1.51359536e-05,
        2.26616889e-14, 1.37563375e-05, 6.28967064e-06, 1.78580702e-14,
        1.46663893e-04, 6.22853191e-09],
       [2.65649146e-06, 9.98999536e-01, 1.52888970e-04, 1.22235424e-05,
        1.03288570e-04, 1.66750815e-05, 3.62318424e-05, 4.83604759e-04,
        1.91218409e-04, 1.74122772e-06],
       [9.90487635e-01, 1.67087236e-07, 4.11861530e-03, 1.38330279e-06,
        1.69170438e-04, 2.56754556e-05, 4.66038473e-03, 2.05710923e-04,
        3.97161557e-06, 3.27171379e-04],
       [8.42753889e-06, 1.05851683e-09, 2.39992623e-05, 2.66158420e-08,
        9.99412656e-01, 6.63739073e-08, 6.52193103e-06, 3.42875792e-05,
        5.89017134e-07, 5.13361301e-04]], dtype=float32)>